POST  http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "whkashjkjhjghjgkhkjdjow",
    "author":"wowk jhshkjhjhdjhghjakjhasjkhd",
    "url":"isthis",
    "likes" :5,
    "userId" : "67b20f05778ab4d47f2edddf"
}